### ISSUE TITLE
Improve uncurrency filters

### ISSUE THREAD

**Issue by leodido** [leodido/moneylaundry#5]
- [x] recognize and handle localised infinity and NaN values (see #10)
- [x] new option `currency_code` (see #6) 
- [x] fix bug related to the change of locale (see #8)
- [x] refactoring
- [x] tests
